### ISSUE TITLE
Review of the "01 - Pandas and Data Wrangling"

### ISSUE THREAD

**Issue by sandrobarna** [vidit09/ada-homework#3]
I think overall it was fine. However, I would suggest making the output more clear to understand next time. For instance, you could have used hierarchical index to identify records in the second notebook (exercise 3). Also, I would recommend to try to use more python language features to keep the code shorter.

**Comment by vidit09** [comment]
Thankyou @sandrobarna for you constructive comments, we will incorporate your feedback in next exercise.
