### ISSUE TITLE
Peer-Review 

### ISSUE THREAD

**Issue by CriMenghini** [vidit09/ada-homework#5]
Hey guys,

first of all good job 👍 

I'm gonna write down few comments and suggestions about the work :)
- Exercise 1
  The exercise has been done in a proper way.

_Suggestions:_
For the next time I suggest you to make functions that generalise the code and can be reused during the pipeline. I see that you define the possible values of the parameters going through the module on `IS Academia` web page, another way to extract them would have been scraping the initial web page and parse it. Instead of loops through year and bachelor just to loop over the bachelor would have been fine, since the web site gives back results for all the years.

Moreover, for the tidiness of the code, you can push them in external hand-made `.py` files. (If there are pieces of code that should be run, try to remove them, only to make the Python notebook more readable)

You write a lot, and it’s very good! The only thing is that maybe you can show the way you obtain such results in terms of code. 
- Exercise 2

The assumptions on the master students are not clear everywhere.
When you do the one-sample test, you specify that the assumptions stand, it would be fine for the reader to see that :D (When you run the tests, you had warnings that are due to the fact that some specialisation are taken just by one student, hence the test can’t be run :) )
- Bonus 

The task wasn’t the one you accomplish, you have to compute the average stay of male and female each year..

**Comment by vidit09** [comment]
Thank you for your elaborate comments. We will try to incorporate them in upcoming homework's.
